# Generated by Django 2.2 on 2019-04-19 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Add_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=30)),
                ('category', models.CharField(default='', max_length=30)),
                ('quantity', models.CharField(default='', max_length=30)),
                ('amount', models.FloatField(default='')),
                ('price', models.FloatField(default='')),
                ('date', models.DateField(default=datetime.datetime(2019, 4, 19, 10, 56, 10, 391015))),
                ('desc', models.CharField(default='', max_length=30)),
                ('mfd', models.CharField(default='', max_length=30)),
                ('exd', models.CharField(default='', max_length=30)),
                ('gst', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Add_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('uname', models.CharField(default='', max_length=30)),
                ('number', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
