# Generated by Django 2.2 on 2019-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrdct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='', max_length=60)),
                ('product', models.CharField(default='', max_length=60)),
                ('date', models.CharField(default='', max_length=60)),
                ('time', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='', max_length=60)),
                ('product', models.CharField(default='', max_length=60)),
                ('date', models.CharField(default='', max_length=60)),
                ('quantity', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SaleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.CharField(default='', max_length=60)),
                ('clientname', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=60)),
                ('paid', models.CharField(default='', max_length=60)),
                ('due', models.CharField(default='', max_length=60)),
                ('total', models.CharField(default='', max_length=60)),
                ('discout', models.CharField(default='', max_length=60)),
                ('grand', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
