# Generated by Django 2.2 on 2019-04-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_staff',
            name='Email',
        ),
        migrations.AddField(
            model_name='add_staff',
            name='uname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
